package ru.cookedapp.insetsvisualizer

enum class InsetsType {
    STATUS_BARS,
    STATUS_BARS_IGNORING_VISIBILITY,
    NAVIGATION_BARS,
    NAVIGATION_BARS_IGNORING_VISIBILITY,
    CAPTION_BAR,
    CAPTION_BAR_IGNORING_VISIBILITY,
    TAPPABLE_ELEMENT,
    TAPPABLE_ELEMENT_IGNORING_VISIBILITY,
    SYSTEM_GESTURES,
    MANDATORY_SYSTEM_GESTURES,
    IME,
    WATERFALL,
    DISPLAY_CUTOUT;
}